class CustomError(Exception):
    pass

class OutOfBoundsError(CustomError):
    pass




